### ISSUE TITLE
Add a simple HTTP service which handles put/get in plain text

### ISSUE THREAD

**Issue by hbs** [facebookincubator/beringei#13]
Grafana integration is great but JSON is not the best choice to integrate Beringei into other environments.

Having an HTTP based service which accepts as input content in the form

key value [timestamp]

and outputs a similar format when queried would be a great basis for building libraries in various languages.

This addition would allow for immediate integration in Warp 10 (www.warp10.io) to provide advanced analytics to data residing in Beringei.

**Comment by kiranisaac** [comment]
@hbs Could verify that https://github.com/facebookincubator/beringei/pull/18 has the required has the right input/output format for integration with Warp 10?

**Comment by jteller** [comment]
Closing this issue - looks to me like #18 will cover this, if implemented correctly
