### ISSUE TITLE
Build break

### ISSUE THREAD

**Issue by cbanek** [facebookincubator/beringei#19]
After pulling down the repo to play around with this, I used the docker container to attempt to build everything, and hit the following build break (also on CI):

https://circleci.com/gh/facebookincubator/beringei/6

Looks like commit 9ae0dde2faee751d1fe3933fe159835d36bdd906 updating the path for this header is relying on later versions of the dependent repos than are pinned in  setup_ubuntu.sh

Not sure if that commit should be reverted, or versions of dependencies updated to reflect this change.

**Comment by kiranisaac** [comment]
@cbanek: Thanks for reporting this issue! We are aware of this issue. I am working on upgrading the  wangle & fbthrift to version 2017.01.16. Unfortunately, folly doesn't have that version tag.

**Comment by jteller** [comment]
445d0ed1e1bd5f2d2148fb9ef84f1c276b5c7f35 fixes this

**Comment by cbanek** [comment]
Builds clean, thanks!
