### ISSUE TITLE
Grafana suport

### ISSUE THREAD

**Issue by roldancer** [facebookincubator/beringei#22]
Hi, Is there any plugin available for Grafana? or any other visualization tool ?

Thanks.

**Comment by mlgood** [comment]
We have an integration with Grafana under beringei/tools/grafana_read_service.

**Comment by kiranisaac** [comment]
Yes, we have an integration with Grafana. You can run grafana_read_service and connect to it using the SimpleJson plugin https://grafana.net/plugins/grafana-simple-json-datasource.

We have only implemented the Query API. Search and Annotations have not been implemented.
