### ISSUE TITLE
Failure using setup_ubuntu.sh, "does NOT support .pth files"

### ISSUE THREAD

**Issue by bassdread** [facebookincubator/beringei#23]
On Ubuntu 16.10 on a clean git checkout of the master branch, running sudo ./setup_ubuntu.sh gives the following error:

```
make[4]: Entering directory '/tmp/fbthrift-2016.11.07.00/thrift/compiler/py'
test -z "" || mkdir -p /lib/python
test -z "" || mkdir -p
/usr/bin/python setup.py install --root=
running install
Checking .pth file support in usr/local/lib/python2.7/dist-packages/
/usr/bin/python -E -c pass
TEST FAILED: usr/local/lib/python2.7/dist-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    usr/local/lib/python2.7/dist-packages/

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://pythonhosted.org/setuptools/easy_install.html#custom-installation-locations

Please make the appropriate changes for your system and try again.
Makefile:762: recipe for target 'install-exec-am' failed
make[4]: *** [install-exec-am] Error 1
make[4]: Leaving directory '/tmp/fbthrift-2016.11.07.00/thrift/compiler/py'
Makefile:642: recipe for target 'install-am' failed
make[3]: *** [install-am] Error 2
make[3]: Leaving directory '/tmp/fbthrift-2016.11.07.00/thrift/compiler/py'
Makefile:935: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/tmp/fbthrift-2016.11.07.00/thrift/compiler'
Makefile:1092: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/tmp/fbthrift-2016.11.07.00/thrift/compiler'
Makefile:499: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

```

Following the advice from the error I tried ```export PYTHONPATH=/usr/local/lib/python2.7/dist-packages/``` and still got the same error.

**Comment by linuxfood** [comment]
Huh. I'll see if I can repro in a fresh ubuntu 16.10 container. I don't think I've seen this issue before.

**Comment by linuxfood** [comment]
I wasn't able to repro on a fresh ubuntu 16.10 container. Can you provide some more details about your environment?

**Comment by bassdread** [comment]
Hi, it's Desktop installation of Ubuntu. I recently upgraded from 16.04 to 16.10. Default Python is 2.7.12. I have tried the suggestions in the error with no success.

**Comment by kiranisaac** [comment]
@bassdread Could you try the temporary workaround mentioned in https://github.com/facebook/fbthrift/issues/193

**Comment by cbanek** [comment]
Just to chime in here, I'm on 16.04 and have also seen this behavior.  It's the only problem in having it work on 16.04, and once I've gotten past that, I'm able to run things.

I believe I ended up editing the makefile in that directory, fixing the path referenced in facebook/fbthrift#193 which ended up getting passed to python install, and that got me unblocked.

**Comment by kiranisaac** [comment]
@bassdread Are you ok with us closing this Issue?

**Comment by kiranisaac** [comment]
I think this issue is resolved. 

@cbanek: Thanks for confirming that the temporary workaround works.

**Comment by bassdread** [comment]
Yup, sorry for the late reply.

**Comment by vritxii** [comment]
I have same problem 
`Checking .pth file support in usr/lib/python3/dist-packages/
/usr/bin/python3 -E -c pass
TEST FAILED: usr/lib/python3/dist-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    usr/lib/python3/dist-packages/

and your PYTHONPATH environment variable currently contains:

    ''

`

And i modify the python common in the Makefile
install: all
	python3 setup.py install --root="/" --no-compile --install-layout=deb
the default value of root is --root="DESTDIR"
After i change to "/", it complied successful
good luck to you

**Comment by liqimore** [comment]
@vritxii 
nice work! this perfectly fixed my problems. 
With `python3 setup.py install --root="/" --prefix=~/custom_packge` You can install&complie you packge in a custom directory.
