### ISSUE TITLE
Fresh Ubuntu - Clang-Format?

### ISSUE THREAD

**Issue by u382514** [facebookincubator/beringei#24]
On a fresh install of an Ubuntu 16.04 the Setup file fails at clang-format-3.9. Possibly add/check the correct repositories at the beginning of the file to pull from (unless I'm doing something wrong then please correct me).

Thanks for this project!

**Comment by kiranisaac** [comment]
clang-format-3.9 is not available on Ubuntu 16.04. Our tested/supported version is Ubuntu 16.10.

If you don't plan to contribute to Beringei, you can remove that line (21) from setup_ubuntu.sh. You don't need clang-format to build/deploy/test Beringei. 

We recommend that you use Ubuntu 16.10.

**Comment by kiranisaac** [comment]
@u382514 Are you ok with us closing this issue?

**Comment by u382514** [comment]
Yes sir! I missed the part in the readme that clearly stated that this was tested in 16.10. My fault!
