### ISSUE TITLE
support redhat and macox 

### ISSUE THREAD

**Issue by ychtiger** [facebookincubator/beringei#25]
Hi, my development environment is macos, can you support more script for other os?

**Comment by linuxfood** [comment]
Unfortunately, we don't have enough resources to support more platforms right now. 

For what it's worth, you can run beringei on CentOS/Redhat, we just don't support it right now. Mostly these distributions have libraries that are just too old. So, you'll need to build a lot more yourself.

**Comment by linuxfood** [comment]
For MacOS, right now I'd guess that it's probably last on our list of platforms we want to support, since our target is large servers. The good news for you is that you can run docker on MacOS, and there is an Ubuntu16.10 container that will work great.
