### ISSUE TITLE
BucketMap::deleteOldBlockFiles is not called

### ISSUE THREAD

**Issue by colerowen** [facebookincubator/beringei#32]
it seems that BucketMap::deleteOldBlockFiles is not called?

**Comment by jteller** [comment]
You are right -- looks like we missed porting the "cleaner thread" over to the open source service handler.

Diff coming up

**Comment by jteller** [comment]
https://github.com/facebookincubator/beringei/pull/34 to add in the cleaner thread (which is what calls that file).
