### ISSUE TITLE
getData failed. Reason: N6apache6thrift9transport19TTransportExceptionE: Channel is !good()

### ISSUE THREAD

**Issue by colerowen** [facebookincubator/beringei#35]
when i use the clientImpl  to get data from beiringei using multithreads ,   "BeringeiNetworkClient.cpp:203] getData failed. Reason: N6apache6thrift9transport19TTransportExceptionE: Channel is !good()" appears. 
What will cause this?

**Comment by jteller** [comment]
We need way more info to answer this question ... how are you actually using the client?

However, the get() method is not thread safe - so if you try to use the client from multiple threads simultaneously, you will get errors like this.

**Comment by colerowen** [comment]
Ten threads keep running ,  each thread runs as follows:
while(1)
{
	for(int i=0;i<FLAGS_pointsPerRound; i++)
	{
		gorilla::GetDataRequest request;
		request.keys.emplace_back();
		request.keys.back().key = m_keyList[pos];
		request.keys.back().shardId = std::hash<std::string>()(request.keys.back().key) % m_shardCount;
		request.begin = start_time;
		request.end = end_time;
	
		gorilla::GorillaResultVector result;
		m_client->get(request, result);       
	}
	
	std::this_thread::sleep_for(xx);
}

~when pointsPerRound is set to larger than 2500 ,   "Channel is !good() " just appears.

**Comment by jteller** [comment]
To fix this, you'll need to create a new client for each thread, as m_client (which looks to be shared across threads) is not thread safe.

```
while(1) {
    auto perThreadClient =
      std::make_shared<gorilla::BeringeiClient>(m_sharedConfigAdaptor, 1, 0, false);
  for(int i=0;i<FLAGS_pointsPerRound; i++) {
    gorilla::GetDataRequest request;
    request.keys.emplace_back();
    request.keys.back().key = m_keyList[pos];
    request.keys.back().shardId = std::hashstd::string()(request.keys.back().key) % m_shardCount;
    request.begin = start_time;
    request.end = end_time;

    gorilla::GorillaResultVector result;
    perThreadClient->get(request, result);       
  }	
  std::this_thread::sleep_for(xx);
}
```

**Comment by colerowen** [comment]
thanks ,it solves my problem.

**Comment by mlgood** [comment]
Glad your issue is solved!  I'll go ahead and close then :)
