### ISSUE TITLE
[question] How to handle replication?

### ISSUE THREAD

**Issue by shanson7** [facebookincubator/beringei#36]
Beringei is blazing fast for reads and writes, which makes it a natural choice for a write-through cache for almost any TSDB out there. With Beringei in front of long-term persistent storage mechanisms, roll-ups/aggregations/bulk writes become trivial to implement (compared to streaming/dynamic partitioning). However, losing a node may lead to downtime if the queries needed for these operations. Replication is a typical method for reducing the chances of downtime due to the loss of a few nodes.

What are the ideas/recommendations for replication with Beringei?

**Comment by linuxfood** [comment]
The way we handle this is by putting the on disk recovery information on shared storage and then having multiple shards for each cluster of Berengei. When a node dies we update the shard map (which node owns which shards) and another node will recover from the shared storage. Basically, Beringei delegates this problem to your file system and configuration distribution systems. We tried to make it generic enough that the implementation requirements were low.

**Comment by linuxfood** [comment]
To do this with your deployment, when you generate the config using `./beringei/tools/beringei_configuration_generator --host_names $(hostname) --file_path /tmp/beringei.json` (from the README) by default if you give us more than one host name, we'll assign shards to hosts in a round-robin fashion, however you're free to use whatever mechanism you want to update or create the assignment. You'll need to ensure that both the client and the servers see the same version using some form of external coordination. Though Beringei will make sure to inform the client if it thinks it has an out of date map.

Hopefully this answers your question!

**Comment by kiranisaac** [comment]
To add to @linuxfood's answer, Beringei Client can write to multiple Beringei Services. We run multiple services internally and always write to all of them. When a node is restarted or an update is being performed, our configuration management system makes sure that we don't read from that service/node.

**Comment by shanson7** [comment]
Interesting stuff!
@linuxfood - Is this a dynamic configuration or does reassigning the shards require node restarts? Have you automated this via an external process?
@kiranisaac - Are you saying that you have multiple copies of the data in memory? How do you deal with partial successes? Is this an active/active set up?

I think these solutions are feasible. I was thinking down the path of automated replicas via some sort of hash chain (i.e. if the data is meant for shard X, give it to the owner of shard X, X+1 and X+2 so long as none of those hosts already has a copy (e.g. shard X and X+2 are in the same process, then go to X+3).

**Comment by linuxfood** [comment]
@shanson7 nodes automatically reload the config on a regular basis, and so pick up new shard assignments too. Internally we have a system called ShardManager that tightly integrates with our infrastructure and uses zookeeper for keeping state, so we don't actually use this config based implementation of sharding. One of the key problems that is left unsolved here is load balancing, unfortunately. Though, for most purposes we expect it shouldn't be a problem, because a single beringei node is so efficient.

**Comment by kiranisaac** [comment]
Yes, we have multiple Beringei Services (each service has multiple hosts) that keep the data in memory. For reads, yes, it is an active-active setup where the client routes to the closest  read enabled Beringei service.  Regarding partial successes, we disable the service for reads if there is a significant drop. If the data drop is small and for a short duration, we don't do anything.

**Comment by shanson7** [comment]
Does this mean that a Service that experienced a failure/downtime is out of read availability until the gap "times out" (e.g. 24 hours if you are keeping 1-day in Beringei)?

**Comment by mlgood** [comment]
Slight correction: we have a little more resilience than has been mentioned above and do not necessarily have to disable a tier from reads if there is a small drop in availability. 

There is a status code Beringei can return called MISSING_TOO_MUCH_DATA which beringei uses when it realizes that it has some data, but has gaps.  The logic for when that status code is used is in service/BeringeiServiceHandler::getData().

The read client will try another beringei (if available) if it receives that status message, but if the last beringei service it talks to reports MISSING_TOO_MUCH_DATA still, it will retry with arguments passed that accept whatever data is available (code is in client/BeringeiClientImpl.cpp, get() and getWithClient() methods).

**Comment by shanson7** [comment]
Ah, yes. Ok, this makes sense then.

So, in summary, multiple Beringei Services are running with independent copies of the data. Writes go to all of them, reads are balanced with failover logic if significant gaps are found.

If a node drops out of the Service cluster, other nodes pick up it's shards (using ZK to manage who get what) and recover the shard states from the shared filesystem.

**Comment by mlgood** [comment]
@shanson7 yup, that's how it works.  Do you have other questions here, or have we addressed this issue?

**Comment by shanson7** [comment]
Do you think there is a place for in-Service replicas (i.e. single Service maintains multiple copies)?

I can think of cases like rolling restarts where in the multi-Service case, there would be non-aligned gaps (e.g. Service 1 had restarts in the morning and therefore gaps, Service 2 had them in the afternoon. If you query for all day, both services have gaps, but together they present the whole picture).

In the single-Service with replicas case, as instances restart then the replicas can continue handling writes and the restarted instance can pick up the gap from one of the replicas. This means that the Service itself is handling the write replication AND the gap filling (rather than the client).

**Comment by linuxfood** [comment]
@shanson7 The way we handle that sort of thing is that we have a query engine and metadata service outside Beringei, the query engine asks the metadata service to do the complex regex/prefix/postfix/etc matching, and then issues precise queries to Beringei based on those results. This is nice because it keeps each component self contained and doing one primary job.

In general, we haven't needed in-service replicas, partially because we fill our replicas up entirely (storing 10 billion time-series in RAM has some costs), but also because we move the shards as part of bringing an instance down for restart.

**Comment by shanson7** [comment]
Re: query service outside of Beringei - Doesn't that mean a lot of network chatter for aggregations on high cardinality tags? For instance, sum/count/avg request times across all users could be done more efficiently by computing partial aggregations locally and sending those back instead of all the raw data.

Re: Moving shards for restarts - Duh, that makes a lot of sense! I didn't think of that 😄

**Comment by linuxfood** [comment]
Query service: We get a lot of benefits from separating the compute from the storage work. It's easier to characterize each individual workload, and tune appropriately than it is to handle a mixed compute+storage workload. These things often need different resources from the hardware, and can often interfere with each other.

**Comment by linuxfood** [comment]
@shanson7 I'm going to close out this issue. Feel free to reopen if you have any more questions :)

**Comment by richardzhangrui** [comment]
@linuxfood Hi! We are very interested in using Beringei as our short term metrics system. You mentioned internally FB uses a metadata service to handle regex/prefix/postfix/etc matching. Would this metadata service become a bottleneck when data loading and querying?  Also how can you make sure metadata and data in Beringei is consistent? 
Thank you!
