### ISSUE TITLE
correcting timestatmp to now leads to  inaccuracy

### ISSUE THREAD

**Issue by colerowen** [facebookincubator/beringei#38]
timestatmp will be correct to now if it lags behind of or lead now too much.
this will be done in BeringeiServiceHandler::putDataPoints() as belows：
if (dp.value.unixTime < now - FLAGS_allowed_timestamp_behind) {
      dp.value.unixTime = now;
      GorillaStatsManager::addStatValue(kDatapointsBehind);
    }

    if (dp.value.unixTime > now + FLAGS_allowed_timestamp_ahead) {
      dp.value.unixTime = now;
      GorillaStatsManager::addStatValue(kDatapointsAhead);
    }

why not just drop this point， since correcting timestamp leads to inaccuracy which may not be expected.

**Comment by mlgood** [comment]
There isn't a clear decision here that's right in all contexts.  In our setup, we've made the decision that its better to keep the data and make the timestamp something that beringei can accept rather than drop data entirely.
