### ISSUE TITLE
Error setup on Ubuntu 16.04.2

### ISSUE THREAD

**Issue by baolinCloud** [facebookincubator/beringei#39]
I got the same issue with https://github.com/facebook/folly/issues/571

Should I modify something?

**Comment by jteller** [comment]
This is the same as https://github.com/facebookincubator/beringei/issues/24

Our tested/supported version is Ubuntu 16.10 - so we recommend that you use Ubuntu 16.10.

**Comment by baolinCloud** [comment]
OK,thanks!
