### ISSUE TITLE
Beringei Java Client

### ISSUE THREAD

**Issue by mszone** [facebookincubator/beringei#41]
Hi, 

We are working on Java Client Binding for Beringie & also adding the tags support. Please let us know how to submit our code to Beringei. Here is the initial version (we will update the documentation soon)  https://github.com/wowcoders/tspark
https://github.com/wowcoders/tspark/tree/master/beringeiclient includes the java client and https://github.com/wowcoders/tspark/tree/master/TSPark contains the query service that supports the tags. 

Thanks,
Venkat

**Comment by linuxfood** [comment]
Hi, thanks for being interested in Beringei!

We really appreciate the work you've put into this. Unfortunately, at this time we don't have the resources to help support a Java client in the main repository. Beringei is under active development internally, and our focus is on the service itself, and really good C++ clients first.

Please do keep us updated with the development progress and feel free to open issues as needed.

**Comment by linuxfood** [comment]
I'm going to close this out for now. Thanks again!
