### ISSUE TITLE
putDataPoints() issue, shard is not owned

### ISSUE THREAD

**Issue by mihaivolmer** [facebookincubator/beringei#44]
I am currently using the `beringei_put` and `beringei_get` utilities. I am running everything locally, so I use a simple configuration with `localhost` as hostname. Also, I am using Ubuntu 17.04.
Whenever I try to insert data, I have the following issue: 
When `putDataPoints()` is called, the program flow always ends up in the branch for shard not owned ([code link](https://github.com/facebookincubator/beringei/blob/master/beringei/service/BeringeiServiceHandler.cpp#L335)).
Also, when `getData()` is called it returns status code 1, which is `StatusCode::DONT_OWN_SHARD`. The output shows a blank key and no points after that, which is expected since `putDataPoints()` failed.

> I0508 14:05:44.275693 16463 BeringeiGet.cpp:89] Key is in shard_id: 24
> I0508 14:05:44.278391 16463 BeringeiGet.cpp:100] Get whole shard stats:
> I0508 14:05:44.278401 16463 BeringeiGet.cpp:101] Request status: 1
> I0508 14:05:44.278409 16463 BeringeiGet.cpp:102] Keys: 

I tried following the code further into the BucketMap implementation but I did not find anything that could help me.

Am I missing something?

**Comment by mlgood** [comment]
Have you configured a beringei configuration file, as described in the README?  BeringeiConfigurationAdapter (under plugins/) reads the config file to determine which shards are owned by which hosts.  It sounds like the config doesn't yet exist showing that the host owns that shard, so beringei is refusing to putDataPoints (and likewise, can't serve get requests).

**Comment by mihaivolmer** [comment]
@mlgood Yes, I have created one with the following command
> ./beringei/tools/beringei_configuration_generator --host_names "localhost" --file_path ./beringei.json

Also, I noticed that `beringei_main`, `beringei_put` and `beringei_get` will crash when the configuration file is not present. I have used the same configuration file for each of them.
Basically, I followed the instructions from the README line by line with above-mentioned result.

**Comment by mlgood** [comment]
I'm sorry for the delay in responding @mihaivolmer.  A few more questions: how long have you typically waited before issuing the call?  Has this line: 
https://github.com/facebookincubator/beringei/blob/master/beringei/service/BeringeiMain.cpp#L78
printed on the server you are talking to?   

I suspect the answer to be "yes" but want to rule out the easy problems first.

**Comment by mlgood** [comment]
@mihaivolmer just checking in, is there still an issue here?

**Comment by mlgood** [comment]
@mihaivolmer I'm going to close this issue since there hasn't been an update.  If you encounter issues in the future, please feel free to open a new issue.
