### ISSUE TITLE
Not able to install beringei on EC2 machine.

### ISSUE THREAD

**Issue by devvsda** [facebookincubator/beringei#45]
I tried to install beringei on AWS EC2 machine, but it is failing while executing bash script -
 "setup_ubuntu"

**Failing at-**

> pushd fbthrift-${FB_VERSION}/thrift
> autoreconf -ivf
> ./configure --prefix=/usr/local/facebook-${FB_VERSION}
> make install
> popd
> 

**Exception** -

> thrift 32.0
> 
> Building C++ Library ......... : yes
> 
> If something is missing that you think should be present,
> please skim the output of configure to find the missing
> component.  Details are present in config.log.
> + make install
> Making install in compiler
> make[1]: Entering directory `/tmp/fbthrift-2017.05.08.00/thrift/compiler'
> make  install-recursive
> make[2]: Entering directory `/tmp/fbthrift-2017.05.08.00/thrift/compiler'
> Making install in .
> make[3]: Entering directory `/tmp/fbthrift-2017.05.08.00/thrift/compiler'
> /bin/bash ../libtool  --tag=CXX   --mode=link g++  -std=gnu++1y -lcrypto -lglog -lmstch -lboost_filesystem -lboost_system -L/usr/local/facebook/lib -Wl,-rpath=/usr/local/facebook/lib  -o thrift1 main.o generate/common.o generate/t_generator.o generate/t_concat_generator.o generate/t_mstch_generator.o generate/t_android_lite_generator.o generate/t_cocoa_generator.o generate/t_cpp_generator.o generate/t_csharp_generator.o generate/t_d_generator.o generate/t_erl_generator.o generate/t_go_generator.o generate/t_hack_generator.o generate/t_hs_generator.o generate/t_html_generator.o generate/t_java_generator.o generate/t_js_generator.o generate/t_mstch_py3_generator.o generate/t_mstch_swift_generator.o generate/t_ocaml_generator.o generate/t_perl_generator.o generate/t_php_generator.o generate/t_py_generator.o generate/t_rb_generator.o generate/t_st_generator.o generate/t_xsd_generator.o -lfl libparse.la libthriftcompilerbase.la 
> libtool: link: g++ -std=gnu++1y -Wl,-rpath=/usr/local/facebook/lib -o thrift1 main.o generate/common.o generate/t_generator.o generate/t_concat_generator.o generate/t_mstch_generator.o generate/t_android_lite_generator.o generate/t_cocoa_generator.o generate/t_cpp_generator.o generate/t_csharp_generator.o generate/t_d_generator.o generate/t_erl_generator.o generate/t_go_generator.o generate/t_hack_generator.o generate/t_hs_generator.o generate/t_html_generator.o generate/t_java_generator.o generate/t_js_generator.o generate/t_mstch_py3_generator.o generate/t_mstch_swift_generator.o generate/t_ocaml_generator.o generate/t_perl_generator.o generate/t_php_generator.o generate/t_py_generator.o generate/t_rb_generator.o generate/t_st_generator.o generate/t_xsd_generator.o  -lglog -lmstch -L/usr/local/facebook/lib -lfl ./.libs/libparse.a ./.libs/libthriftcompilerbase.a -lcrypto -lboost_filesystem -lboost_system
> generate/t_mstch_generator.o: In function `t_mstch_generator::render(std::string const&, boost::variant<boost::detail::variant::recursive_flag<decltype(nullptr)>, std::string, int, double, bool, mstch::internal::lambda_t<boost::recursive_variant_>, std::shared_ptr<mstch::internal::object_t<boost::recursive_variant_> >, std::map<std::string const, boost::recursive_variant_, std::less<std::string const>, std::allocator<std::pair<std::string const, boost::recursive_variant_> > >, std::vector<boost::recursive_variant_, std::allocator<boost::recursive_variant_> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const':
> t_mstch_generator.cc:(.text+0x5b4b): undefined reference to `mstch::render(std::string const&, boost::variant<boost::detail::variant::recursive_flag<decltype(nullptr)>, std::string, int, double, bool, mstch::internal::lambda_t<boost::recursive_variant_>, std::shared_ptr<mstch::internal::object_t<boost::recursive_variant_> >, std::map<std::string const, boost::recursive_variant_, std::less<std::string const>, std::allocator<std::pair<std::string const, boost::recursive_variant_> > >, std::vector<boost::recursive_variant_, std::allocator<boost::recursive_variant_> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&)'
> collect2: error: ld returned 1 exit status
> make[3]: *** [thrift1] Error 1
> make[3]: Leaving directory `/tmp/fbthrift-2017.05.08.00/thrift/compiler'
> make[2]: *** [install-recursive] Error 1
> make[2]: Leaving directory `/tmp/fbthrift-2017.05.08.00/thrift/compiler'
> make[1]: *** [install] Error 2
> make[1]: Leaving directory `/tmp/fbthrift-2017.05.08.00/thrift/compiler'
> make: *** [install-recursive] Error 1

**EC2 machine details**-
I tried on  Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-74-generic x86_64), and 16.04 ubuntu version machine.

I suspect some library is missing, please guide how to fix this ?

**Comment by linuxfood** [comment]
Do you have a complete log? It looks like the `mstch` installation either wasn't complete, or there's been some drift in the libraries that we need to fix.

**Comment by devvsda** [comment]
[setup_logs.txt](https://github.com/facebookincubator/beringei/files/1021909/setup_logs.txt)

Attached logs of setup_ubuntu.sh script.

**Comment by scottfranklin** [comment]
It looks like you updated the version tag to 2017.05.08.00?

I see a different, but also mstch-related error when building from that version.

That said, it seems to work fine from both the existing 2017.04.24.00 and the newer 2017.05.22.00 tags.

Do you have any other local changes to `setup_ubuntu.sh`?
It's working correctly for me on a clean Ubuntu 16.04 install with this patch applied:
```
diff --git a/setup_ubuntu.sh b/setup_ubuntu.sh
index 1f50477..89e7bab 100755
--- a/setup_ubuntu.sh
+++ b/setup_ubuntu.sh
@@ -1,7 +1,7 @@
 #!/bin/bash
 set -e

-FB_VERSION="2017.04.24.00"
+FB_VERSION="2017.05.22.00"
 ZSTD_VERSION="1.1.1"

 echo "This script configures ubuntu with everything needed to run beringei."
@@ -15,7 +15,6 @@ apt install --yes \
     automake \
     binutils-dev \
     bison \
-    clang-format-3.9 \
     cmake \
     flex \
     g++ \
```

Interestingly, from your logs it looks like it skipped building mstch because of an existing install. I might try wiping `/usr/local/facebook/` and doing a fresh build with the above patch.

**Comment by devvsda** [comment]
I applied your patch, and also deleted 

> rm -rf /usr/local/faebook*

Still it is failing but in different step. Attaching complete log.

[setup_logs.txt](https://github.com/facebookincubator/beringei/files/1030914/setup_logs.txt)

**Comment by scottfranklin** [comment]
That log file doesn't have any errors in it.

It looks like you only captured stdout, not stderr?
You probably want something like `sudo setup_ubuntu.sh 2>&1 > setup_logs.txt`

**Comment by devvsda** [comment]
executed command -> sudo setup_ubuntu.sh 2>&1 > setup_logs.txt

Attached output file. Please check.
[setup_logs.txt](https://github.com/facebookincubator/beringei/files/1033394/setup_logs.txt)

**Comment by devvsda** [comment]
Gentle reminder.

**Comment by linuxfood** [comment]
Apologies on the delay. The 29th was a holiday for us. I've looked closer at the second log you've posted and at the original bug report. There's one main issue. I just saw from your bug report, that you first tried 14.04, and then 16.04. Our minimum requirement for building is Ubuntu **16.10**.

The main issue with those are that the system libraries on them are too old. You *might* be able to get Beringei building on those platforms if you backported at least boost 1.59.0, but, we can't support you because we don't have the people to help validate such a configuration right now. If you're unable to use 16.10 in your main production environment, we do provide a `Dockerfile` that you can use to containerize Beringei.

I'm going to close this out. Please do feel free to open another issue if you try again with 16.10 and still have issues.
