### ISSUE TITLE
How can solve the fbthrift dependency problem on Mac OS X 

### ISSUE THREAD

**Issue by treedom** [facebookincubator/beringei#48]
**Target :** the purpose to build fbthrift is to get the lib(maybe libfbthrift.dylib) to solve the compilation dependency of Beringei(because i find 'find_package(FBThrift REQUIRED)' in its CMakeList.txt)
**Problem :** my os is Max OS sierra and i do :

1)git clone fbthrift

2)cd thrift && thrift && autoreconf -ivf && ./configure && make install

but, in step 2) i get the err :

'Reason: unsafe use of relative rpath libboost_python.dylib in /Users/ted/Work/Code/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.7.egg/thrift_compiler/frontend.so with restricted binary'

then i try :

3) otool -L '/Users/ted/Work/Code/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.7.egg/thrift_compiler/frontend.so' find that libboost_python.dylib is rpath

4)so i used the 'install_name_tool -change' commmand to alter it.

but when i make again, the promble is still go on! and i find everytime i make the 'frontend.so' is refresh. This is to say the step 4) aim to alter rpath is not work at all
**So, My question is :**

1)How can i slove the 'frontend.so' problem on Mac OS

2)How can i build the libfbthrift.dylib first and then to build the Beringei on Mac OS :(

**Comment by manolama** [comment]
You may want to cross-post in the fbthrift project, see if they have any ideas. Otherwise try the Docker file or Vagrant to run Beringei under Mac for now.

**Comment by mlgood** [comment]
@manolama is correct -- we don't currently have support for building beringei directly on Mac OSX without using virtualization/containers.  We currently support Ubuntu 16.10.

**Comment by mlgood** [comment]
@treedom do you have any other questions for us?

**Comment by mlgood** [comment]
I'm going to go ahead and close this issue.  Please feel free to open a new issue if there are problems getting Ubuntu 16.10 set up.
