### ISSUE TITLE
Starting beringei fails

### ISSUE THREAD

**Issue by juesexingqiu** [facebookincubator/beringei#53]
**when i run the command below to start beringei**
./beringei/service/beringei_main \
    -beringei_configuration_path /tmp/beringei.json \
    -create_directories \
    -sleep_between_bucket_finalization_secs 60 \
    -allowed_timestamp_behind 300 \
    -bucket_size 600 \
    -buckets $((86400/600)) \
    -logtostderr \
    -v=2
**a part of result is as follow**
E0808 15:12:03.404348 13065 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:12:03.404367 13065 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:12:03.404386 13065 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:12:03.404404 13065 BucketStorage.cpp:330] Trying to finalize an expired bucket
I0808 15:13:03.403162 12857 BeringeiServiceHandler.cpp:698] Finalizing buckets at time 1502175423
E0808 15:13:03.403259 13069 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:13:03.403266 13069 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:13:03.403270 13069 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:13:03.403272 13069 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:13:03.403275 13069 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:13:03.403277 13069 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:13:03.403280 13069 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:13:03.403282 13069 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:13:03.403285 13069 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:13:03.403291 13069 BucketStorage.cpp:330] Trying to finalize an expired bucket
I0808 15:14:03.404064 12857 BeringeiServiceHandler.cpp:698] Finalizing buckets at time 1502175483
E0808 15:14:03.404425 13073 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:14:03.404515 13073 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:14:03.404659 13073 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:14:03.404868 13073 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:14:03.405040 13073 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:14:03.405102 13073 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:14:03.405407 13073 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:14:03.405568 13073 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:14:03.405678 13073 BucketStorage.cpp:330] Trying to finalize an expired bucket
E0808 15:14:03.405270 13072 BucketStorage.cpp:330] Trying to finalize an expired bucket

**Comment by jteller** [comment]
Could you provide us with more details? To me it looks like Beringei started successfully. I think the messages you sent are benign error messages that happen when no data is written to Beringei and it attempts to finalize an empty bucket.

**Comment by jteller** [comment]
Working on this locally - this may not be a benign error. However, I cannot repro it.

I need more information to help you get to the bottom of the issue. What OS? How are you running it? What is the overall environment you are running in? How many shards? etc, etc

**Comment by juesexingqiu** [comment]
My OS is Ubuntu 16.10。 I only run these commands as follows
step one：sudo ./setup_ubuntu.sh
step two：mkdir build && cd build && cmake .. && make
step three：./beringei/tools/beringei_configuration_generator --host_names $(hostname) --file_path /tmp/beringei.json
step four：
./beringei/service/beringei_main \
    -beringei_configuration_path /tmp/beringei.json \
    -create_directories \
    -sleep_between_bucket_finalization_secs 60 \
    -allowed_timestamp_behind 300 \
    -bucket_size 600 \
    -buckets $((86400/600)) \
    -logtostderr \
    -v=2
Then error occurs “Trying to finalize an expired bucket”. Do you mean this is not an error? Also, I must start Beringei successfully , then i can write data to Beringei? If the sequence is right? My company wants to take Beringei as underlying database of monitor solution, how should we use Beringei correctly?

Is there any specification in detail about Beringei  except Github and that paper about Gorilla?

**Comment by jteller** [comment]
Lots of questions :-)

I mean that this error being printed may not actually impact the running of the service ... or it may indicate that there was a failure at some point before it started printing that line, causing lots of issues. Can you repro this consistently? What revision are you at that you see this error? The build on the master branch is broken at the moment, so you must be running something a little older.

To answer your other questions:
  [q] I must start Beringei successfully, then i can write data to Beringei? Is the sequence right?
  [a] Yes - you must start the server before you write data into it. The example order in the readme  (using beringei_put and beringei_get) works.

  [q] My company wants to take Beringei as underlying database of monitor solution, how should we use Beringei correctly?
  [a] Beringei may be used in one of several ways. You can use it as a library embedded in another (more full featured) monitoring system, useful as an in-memory write through cache. Or, you can stand it up as a simple, sharded, in-memory TSDB service.

  [q] Is there any specification in detail about Beringi except Github and that paper about Gorilla?
  [a] No - but the paper describes the compression algorithm well enough to implement it yourself (see Prometheus for one example that did that), and this code represents a complete solution to storing time series data in a compressed and efficient manner in memory.

**Comment by at15** [comment]
disclaimer, I am not a contributor to beringei, just my personal opinions

For the implementation of compression, you can check out https://github.com/dgryski/go-tsz , both Prometheus and InfluxDB are based on this implementation, and there are some differences with the original paper #17 

And I don't think you should use beringei unless your company's business is monitoring or you have strict requirement for your monitoring, Prometheus, InfluxDB have more complete toolchains, agent, visualization etc (shameless plug, you find more TSDB here https://github.com/xephonhq/awesome-time-series-database)

**Comment by juesexingqiu** [comment]
@jteller 
Thanks a lot! When i compile source code at first time, the error about "SpookyHashV2.h" occurs. So i modify the location of referencing file in some file including the header file and then compile successfully. But when i start Beringei, the error about "Trying to finalize an expired bucket" occurs. I don't know whether the error is related to my modification about the location.

**Comment by juesexingqiu** [comment]
@at15 
Anyway. Thanks. The material you provide is helpful greatly to me.

**Comment by mlgood** [comment]
@juesexingqiu we're aware of the build break and working on a fix:
https://github.com/facebookincubator/beringei/issues/51

This change, locally, should fix the build break:
https://github.com/facebookincubator/beringei/pull/52

If you compile and run it at that point, do you still see the message print?  Also, that message doesn't mean that beringei isn't running, and I've seen it print before in start-up conditions.  How long have you let it run while printing that message?  Does it ever stop printing the message?

**Comment by jteller** [comment]
With little more information on this, I'm inclined to call this issue done. If you want to ask more questions, please let us know though and we will continue investigating!
