### ISSUE TITLE
Data ingestion rate = 1 per 30 seconds ?

### ISSUE THREAD

**Issue by taroplus** [facebookincubator/beringei#55]
Hello, I was running some test and noticed that I can only get datapoint every 30 seconds. The datapoints in between those are dropped.

sending a counter value every second by running this
```
counter=0
while [[ 1 ]]; do
    counter=$((counter+1))
    ./beringei/tools/beringei_put \
        -beringei_configuration_path /tmp/beringei.json \
        testkey ${counter} \
        -logtostderr -v 3
    sleep 1
done
```

Then result for GET is
```
testkey	1	1510347426
testkey	27	1510347456
testkey	53	1510347486
```

What am I missing, is this the expected behavior ?

**Comment by jteller** [comment]
This is controllable via a commandline flag:

https://github.com/facebookincubator/beringei/blob/40584e0636f7e822e753b31ccdfe680ad43dc8ba/beringei/lib/BucketedTimeSeries.cpp#L13-L16

**Comment by jteller** [comment]
add --mintimestampdelta=1 to allow 1 point per second.
