### ISSUE TITLE
How can I use it in the iOS Dev?

### ISSUE THREAD

**Issue by SecondDog** [facebookincubator/beringei#59]
I want to build this libiary for the iOS platform. How to？

**Comment by linuxfood** [comment]
Beringei is intended to store large amounts of time-series data on a server. Specifically its only been tested on x86_64 machines running Ubuntu. Can you provide some more details on what you're trying to do?

**Comment by SecondDog** [comment]
I want to get some sensor data for machine learning which is time based

**Comment by jteller** [comment]
The approach used in Beringei _should_ work fine no matter the platform - but as @linuxfood mentioned, it's wholly untested on anything except for x86_64, and the build environment is not at all setup for iOS.

You won't be able to build this library, as is, and incorporate it in your project. It's an exercise left to the reader to rewrite/modify the code to work on the platform of your choice.
