### ISSUE TITLE
compile thrift IDL failed: Cannot use reserved language keyword: "begin"

### ISSUE THREAD

**Issue by smallfish** [facebookincubator/beringei#68]
Hi,

I used other language client to test beringei, compiled thrift(version: `0.11.0`) IDL like:

```
$ thrift -I $(pwd) -r -gen py beringei/if/beringei.thrift
...
[ERROR:/home/xx/beringei/beringei/if/beringei.thrift:36] (last token was 'begin')
Cannot use reserved language keyword: "begin"
```

**Comment by smallfish** [comment]
By the way, Ubuntu 16.10 is no longer supported, at new system/container apt-get/install will catched some source 404 not found errors...

**Comment by at15** [comment]
Are you using fbthrift? https://github.com/facebook/fbthrift And there is a pending PR https://github.com/facebookincubator/beringei/pull/62 for using 17.10

**Comment by smallfish** [comment]
@at15 thanks a lot :)
